# .pre-commit-config.yaml
-   repo: https://github.com/prettier/prettier
    rev: v2.8.1 # Specify the version of Prettier you want to use
    hooks:
    -   id: prettier
        name: Prettier
        files: \.(js|ts|json|css|scss|md)$  # Specify the file types to format

-   repo: https://github.com/eslint/eslint
    rev: v8.0.0 # Specify the version of ESLint
    hooks:
    -   id: eslint
        name: ESLint
        files: \.(js|ts)$  # Specify the file types to lint
        args: ['--max-warnings', '0']  # Optionally set ESLint arguments

-   repo: https://github.com/pre-commit/mirrors-black
    rev: v22.3.0 # Specify the version of Black (for Python code formatting)
    hooks:
    -   id: black
        name: Black
        files: \.py$
        args: ['--line-length', '79']  # Set custom arguments for Black

-   repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.1 # Specify the version of Flake8 (Python linting)
    hooks:
    -   id: flake8
        name: Flake8
        files: \.py$
        args: ['--max-line-length=79']  # Set custom arguments for Flake8

-   repo: https://github.com/pre-commit/mirrors-pyflakes
    rev: v2.4.0 # Specify the version of Pyflakes
    hooks:
    -   id: pyflakes
        name: Pyflakes
        files: \.py$
        args: ['--max-line-length=79']  # Set custom arguments for Pyflakes

-   repo: https://github.com/dylang/prettier-markdown
    rev: v0.1.0
    hooks:
    -   id: prettier-markdown
        name: Prettier (Markdown)
        files: \.md$
