name: Mailer-Deployment

on:
  push:
    branches:
       - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Greet user
        run: echo "Welcome Mr Dapo"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the Node.js version you want

      - name: Install dependencies
        run: npm install

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/practice-image:1 .

      - name: Verify Docker images
        run: docker images  # List images to verify the build

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/practice-image:1