name: CI/CD

on:
  push:
    branches:
      - main  # Specify the branch to trigger the workflow (use 'main' or 'master' depending on your branch)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Docker image
      - name: Build Docker image
        run: docker build -t dapper01/dmailer:1 .

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push dapper01/dmailer:1
 

