name: Mailer-Deployment

on:
  push:
    branches:
       - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Greet user
        run: echo "Welcome Mr Dapo"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the Node.js version you want

      - name: Install dependencies
        run: npm install

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/practice-image:1 .

      - name: Verify Docker images
        run: docker images  # List images to verify the build

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/practice-image:1

        # Upload artifact  
      - name: Create a File
        run: echo "hello from Build job" > file-Build.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-Build
          path: file-Build.txt


  Deploy:
    needs: Build  # Corrected dependency to Build job
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: my-artifact
          pattern: my-artifact-*
          merge-multiple: true

      - run: ls -R my-artifact

        name: send-email
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Email via Gmail
        uses: dawidd6/action-send-mail@v3
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 587
          from: ${{ secrets.GMAIL_EMAIL }}
          to: recipient@example.com
          subject: 'Test Email'
          body: 'This is a test email sent from GitHub Actions.'
          username: ${{ secrets.GMAIL_EMAIL }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}  # Use the application-specific password
